<!DOCTYPE html>
<html>
<head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>
<!DOCTYPE html>
<html lang="en-us">



<link rel="stylesheet" href="/css/fonts.css">
<link rel="stylesheet" href="/css/main-site.css">
<link rel="stylesheet" href="/css/fa5-all.css">
<style type="text/css">
    /* Google Fonts */


body {
	background-color: <no value>;
	color: <no value>;
}

/* Links */

a {
  color: <no value>;
}

a:hover {
  color: <no value>;
}

a:focus {
  outline-color: <no value>;
}

.column25-left .sectionTitle a:hover:not(.current),
.column16-left .sectionTitle a:hover:not(.current) { /* Tutorial left sidebar */
  color: <no value>;
}

.icon-attribution, 
.icon-attribution a {
  color: <no value>;
  opacity: 75%;
}


/* Landing page content bands */

#homeContent .band.first {
  background-color: <no value>;
}

#homeContent .band.second {
  background-color: <no value>;
}

#homeContent .band.third {
  background-color: <no value>;
}

/* Top navigation bar menu */

#rStudioHeader {
  background-color: <no value>;
  color: <no value>;
}

#rStudioHeader .productName {
  color: <no value>;
}

#rStudioHeader .productName:hover,
#rStudioHeader .productName:focus {
  color: <no value>;
}

#rStudioHeader #menu .menuItem.a {
  background-color: #75aadb;
  color: <no value>;
}

#rStudioHeader #menu .menuItem:hover {
  background-color: <no value>;
  color: <no value>;
}

#rStudioHeader #menu .menuItem.current {
  background-color: <no value>;
  color: <no value>;
  text-decoration: <no value>;
}

/* Footer */

#rStudioFooter.band {
  background-color: <no value>;
}

#rStudioFooter .bandContent #copyright {
  color: <no value>;
}

/* Tables */

table tbody tr:nth-child(even){
  background-color: <no value>;
}

table tbody tr:nth-child(odd){
  background-color: <no value>;
}

.latest {
  border-top: .5em solid <no value>;
}


/* ------Accent Font------- */





/* ----Accent color for headers, toc, etc.----- */



/* Custom colored bullets */



/* ------Capitalization of Headers------- */

  

/* -----Hexes------*/


/*----- Borders------ */



/*--- Event Stickies ---*/


















/* ------Test Drive Button-------*/














 

</style>




<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="generator" content="Hugo 0.147.2">
<title>Iterative Bayesian optimization of a classification model</title>
<meta property="og:title" content="Iterative Bayesian optimization of a classification model" />
<meta property="og:description" content="Identify the best hyperparameters for a model using Bayesian optimization of iterative search.
" />
<meta property="og:type" content="article" />
<meta property="og:url" content="//localhost:1313/learn/work/bayes-opt/" />



<meta property="twitter:card" content="summary_large_image">



<meta property="og:url" content="//localhost:1313/learn/work/bayes-opt/">
  <meta property="og:site_name" content="Education">
  <meta property="og:title" content="Iterative Bayesian optimization of a classification model">
  <meta property="og:description" content="Identify the best hyperparameters for a model using Bayesian optimization of iterative search.">
  <meta property="og:locale" content="en_us">
  <meta property="og:type" content="article">
    <meta property="article:section" content="learn">
    <meta property="article:tag" content="Tune">
    <meta property="article:tag" content="Dials">
    <meta property="article:tag" content="Parsnip">
    <meta property="article:tag" content="Recipes">
    <meta property="article:tag" content="Workflows">

  
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="Iterative Bayesian optimization of a classification model">
  <meta name="twitter:description" content="Identify the best hyperparameters for a model using Bayesian optimization of iterative search.">



<link rel="apple-touch-icon" sizes="180x180" href="/images/favicons/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicons/favicon-16x16.png" />
<link rel="manifest" href="/images/favicons/site.webmanifest" />
<link rel="mask-icon" href="/images/favicons/safari-pinned-tab.svg" />
<link rel="shortcut icon" href="/images/favicons/favicon.ico" />
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" href="/images/favicons/browserconfig.xml" >



<script type="text/javascript" src="/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="/js/site.js"></script>








<link rel="icon" href="/images/favicon.ico" />


  
<script type="text/javascript" src="/js/clipboard.js"></script>






  







  <body>
    <div id="appTidyverseSite" class="shrinkHeader alwaysShrinkHeader">
      <div id="main">
        
        <div id="rStudioHeader">
          <div class="band">
            <div class="innards bandContent">
              <div>
                <a class="productName" href="/">Education</a>
                
              </div>
              <div id="menu">
  <div id="menuToggler"></div>
  <div id="menuItems" class="">
    
    
  </div>
</div>

            </div>
          </div>
        </div>
</head>
<body>


 




<div class="band padForHeader pushFooter">
  <div class="bandContent">
    <div class="full splitColumns withMobileMargins">
      <div class="column75">

      <h1 class="article-title">Iterative Bayesian optimization of a classification model</h1>

      
      <div class="article-header" aria-hidden="true">
          
        
      </div>

      
      
      
      
        </p>

      <div class="article-content">
      



<h2 id="introduction">Introduction
  <a href="#introduction">
    <svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg>
  </a>
</h2><p>To use the code in this article, you will need to install the following packages: kernlab, modeldata, tidymodels, and tidyr.</p>
<p>Many of the examples for model tuning focus on 
<a href="/learn/work/tune-svm/">grid search</a>. For that method, all the candidate tuning parameter combinations are defined prior to evaluation. Alternatively, <em>iterative search</em> can be used to analyze the existing tuning parameter results and then <em>predict</em> which tuning parameters to try next.</p>
<p>There are a variety of methods for iterative search and the focus in this article is on <em>Bayesian optimization</em>. For more information on this method, these resources might be helpful:</p>
<ul>
<li>
<p>
<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Practical&#43;Bayesian&#43;Optimization&#43;of&#43;Machine&#43;Learning&#43;Algorithms&amp;btnG=" target="_blank" rel="noopener"><em>Practical bayesian optimization of machine learning algorithms</em></a> (2012). J Snoek, H Larochelle, and RP Adams. Advances in neural information.</p>
</li>
<li>
<p>
<a href="https://www.cs.toronto.edu/~rgrosse/courses/csc411_f18/tutorials/tut8_adams_slides.pdf" target="_blank" rel="noopener"><em>A Tutorial on Bayesian Optimization for Machine Learning</em></a> (2018). R Adams.</p>
</li>
<li>
<p>
<a href="http://www.gaussianprocess.org/gpml/" target="_blank" rel="noopener"><em>Gaussian Processes for Machine Learning</em></a> (2006). C E Rasmussen and C Williams.</p>
</li>
<li>
<p>
<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=%22Bayesian&#43;Optimization%22&amp;btnG=" target="_blank" rel="noopener">Other articles!</a></p>
</li>
</ul>




<h2 id="cell-segmenting-revisited">Cell segmenting revisited
  <a href="#cell-segmenting-revisited">
    <svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg>
  </a>
</h2><p>To demonstrate this approach to tuning models, let&rsquo;s return to the cell segmentation data from the 
<a href="/start/resampling/">Getting Started</a> article on resampling:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">library</span>(tidymodels)
</span></span><span style="display:flex;"><span><span style="color:#00f">library</span>(modeldata)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic"># Load data</span>
</span></span><span style="display:flex;"><span><span style="color:#00f">data</span>(cells)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#00f">set.seed</span>(<span style="color:#666">2369</span>)
</span></span><span style="display:flex;"><span>tr_te_split <span style="color:#666">&lt;-</span> <span style="color:#00f">initial_split</span>(cells <span style="color:#666">%&gt;%</span> <span style="color:#00f">select</span>(<span style="color:#666">-</span>case), prop <span style="color:#666">=</span> <span style="color:#666">3</span><span style="color:#666">/</span><span style="color:#666">4</span>)
</span></span><span style="display:flex;"><span>cell_train <span style="color:#666">&lt;-</span> <span style="color:#00f">training</span>(tr_te_split)
</span></span><span style="display:flex;"><span>cell_test  <span style="color:#666">&lt;-</span> <span style="color:#00f">testing</span>(tr_te_split)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#00f">set.seed</span>(<span style="color:#666">1697</span>)
</span></span><span style="display:flex;"><span>folds <span style="color:#666">&lt;-</span> <span style="color:#00f">vfold_cv</span>(cell_train, v <span style="color:#666">=</span> <span style="color:#666">10</span>)
</span></span></code></pre></div>



<h2 id="the-tuning-scheme">The tuning scheme
  <a href="#the-tuning-scheme">
    <svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg>
  </a>
</h2><p>Since the predictors are highly correlated, we can used a recipe to convert the original predictors to principal component scores. There is also slight class imbalance in these data; about 64% of the data are poorly segmented. To mitigate this, the data will be down-sampled at the end of the pre-processing so that the number of poorly and well segmented cells occur with equal frequency. We can use a recipe for all this pre-processing, but the number of principal components will need to be <em>tuned</em> so that we have enough (but not too many) representations of the data.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>cell_pre_proc <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">recipe</span>(class <span style="color:#666">~</span> ., data <span style="color:#666">=</span> cell_train) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_YeoJohnson</span>(<span style="color:#00f">all_predictors</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_normalize</span>(<span style="color:#00f">all_predictors</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_pca</span>(<span style="color:#00f">all_predictors</span>(), num_comp <span style="color:#666">=</span> <span style="color:#00f">tune</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_downsample</span>(class)
</span></span></code></pre></div><p>In this analysis, we will use a support vector machine to model the data. Let&rsquo;s use a radial basis function (RBF) kernel and tune its main parameter ($\sigma$). Additionally, the main SVM parameter, the cost value, also needs optimization.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_mod <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">svm_rbf</span>(mode <span style="color:#666">=</span> <span style="color:#ba2121">&#34;classification&#34;</span>, cost <span style="color:#666">=</span> <span style="color:#00f">tune</span>(), rbf_sigma <span style="color:#666">=</span> <span style="color:#00f">tune</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">set_engine</span>(<span style="color:#ba2121">&#34;kernlab&#34;</span>)
</span></span></code></pre></div><p>These two objects (the recipe and model) will be combined into a single object via the <code>workflow()</code> function from the 
<a href="https://tidymodels.github.io/workflows/" target="_blank" rel="noopener">workflows</a> package; this object will be used in the optimization process.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_wflow <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">workflow</span>() <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">add_model</span>(svm_mod) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">add_recipe</span>(cell_pre_proc)
</span></span></code></pre></div><p>From this object, we can derive information about what parameters are slated to be tuned. A parameter set is derived by:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_set <span style="color:#666">&lt;-</span> <span style="color:#00f">parameters</span>(svm_wflow)
</span></span><span style="display:flex;"><span>svm_set
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; Collection of 3 parameters for tuning</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;         id parameter type object class</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;       cost           cost    nparam[+]</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  rbf_sigma      rbf_sigma    nparam[+]</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;   num_comp       num_comp    nparam[+]</span>
</span></span></code></pre></div><p>The default range for the number of PCA components is rather small for this data set. A member of the parameter set can be modified using the <code>update()</code> function. Let&rsquo;s constrain the search to one to twenty components by updating the <code>num_comp</code> parameter. Additionally, the lower bound of this parameter is set to zero which specifies that the original predictor set should also be evaluated (i.e., with no PCA step at all):</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_set <span style="color:#666">&lt;-</span> 
</span></span><span style="display:flex;"><span>  svm_set <span style="color:#666">%&gt;%</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">update</span>(num_comp <span style="color:#666">=</span> <span style="color:#00f">num_comp</span>(<span style="color:#00f">c</span>(<span style="color:#666">0L</span>, <span style="color:#666">20L</span>)))
</span></span></code></pre></div>



<h2 id="sequential-tuning">Sequential tuning
  <a href="#sequential-tuning">
    <svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg>
  </a>
</h2><p>Bayesian optimization is a sequential method that uses a model to predict new candidate parameters for assessment. When scoring potential parameter value, the mean and variance of performance are predicted. The strategy used to define how these two statistical quantities are used is defined by an <em>acquisition function</em>.</p>
<p>For example, one approach for scoring new candidates is to use a confidence bound. Suppose accuracy is being optimized. For a metric that we want to maximize, a lower confidence bound can be used. The multiplier on the standard error (denoted as <code>\(\kappa\)</code>) is a value that can be used to make trade-offs between <strong>exploration</strong> and <strong>exploitation</strong>.</p>
<ul>
<li>
<p><strong>Exploration</strong> means that the search will consider candidates in untested space.</p>
</li>
<li>
<p><strong>Exploitation</strong> focuses in areas where the previous best results occurred.</p>
</li>
</ul>
<p>The variance predicted by the Bayesian model is mostly spatial variation; the value will be large for candidate values that are not close to values that have already been evaluated. If the standard error multiplier is high, the search process will be more likely to avoid areas without candidate values in the vicinity.</p>
<p>We&rsquo;ll use another acquisition function, <em>expected improvement</em>, that determines which candidates are likely to be helpful relative to the current best results. This is the default acquisition function. More information on these functions can be found in the 
<a href="https://tidymodels.github.io/tune/articles/acquisition_functions.html" target="_blank" rel="noopener">package vignette for acquisition functions</a>.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">set.seed</span>(<span style="color:#666">12</span>)
</span></span><span style="display:flex;"><span>search_res <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  svm_wflow <span style="color:#666">%&gt;%</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">tune_bayes</span>(
</span></span><span style="display:flex;"><span>    resamples <span style="color:#666">=</span> folds,
</span></span><span style="display:flex;"><span>    <span style="color:#408080;font-style:italic"># To use non-default parameter ranges</span>
</span></span><span style="display:flex;"><span>    param_info <span style="color:#666">=</span> svm_set,
</span></span><span style="display:flex;"><span>    <span style="color:#408080;font-style:italic"># Generate five at semi-random to start</span>
</span></span><span style="display:flex;"><span>    initial <span style="color:#666">=</span> <span style="color:#666">5</span>,
</span></span><span style="display:flex;"><span>    iter <span style="color:#666">=</span> <span style="color:#666">50</span>,
</span></span><span style="display:flex;"><span>    <span style="color:#408080;font-style:italic"># How to measure performance?</span>
</span></span><span style="display:flex;"><span>    metrics <span style="color:#666">=</span> <span style="color:#00f">metric_set</span>(roc_auc),
</span></span><span style="display:flex;"><span>    control <span style="color:#666">=</span> <span style="color:#00f">control_bayes</span>(no_improve <span style="color:#666">=</span> <span style="color:#666">30</span>, verbose <span style="color:#666">=</span> <span style="color:#008000;font-weight:bold">TRUE</span>)
</span></span><span style="display:flex;"><span>  )
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; &gt;  Generating a set of 5 initial parameter results</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Initialization complete</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; Optimizing roc_auc using the expected improvement</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 1 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.58, rbf_sigma=1.54e-09, num_comp=12</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8624 (+/-0.00897)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 2 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0251, rbf_sigma=6.36e-06, num_comp=16</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8606 (+/-0.00908)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 3 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=23, rbf_sigma=1.02e-10, num_comp=7</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8634 (+/-0.00923)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 4 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0894, rbf_sigma=1.09e-10, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8494 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 5 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.402, rbf_sigma=0.413, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8236 (+/-0.00885)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 6 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=24, rbf_sigma=0.942, num_comp=8</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8054 (+/-0.0114)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 7 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=30.3, rbf_sigma=2.25e-06, num_comp=13</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8622 (+/-0.009)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 8 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=25, rbf_sigma=1.07e-10, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8655 (+/-0.00848)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 9 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=2.1, rbf_sigma=5.29e-06, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8494 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 10 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8655 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=9.87, rbf_sigma=0.000395, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8681 (+/-0.00898)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 11 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8681 (@iter 10)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.073, rbf_sigma=0.000585, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8509 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 12 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8681 (@iter 10)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00101, rbf_sigma=1.29e-07, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8494 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 13 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8681 (@iter 10)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0553, rbf_sigma=0.000291, num_comp=12</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8625 (+/-0.00898)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 14 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8681 (@iter 10)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=11.8, rbf_sigma=0.00143, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8691 (+/-0.00837)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 15 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8691 (@iter 14)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0915, rbf_sigma=0.03, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8728 (+/-0.00842)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 16 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0289, rbf_sigma=8.48e-09, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8655 (+/-0.00848)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 17 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0021, rbf_sigma=0.0109, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8696 (+/-0.00881)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 18 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.461, rbf_sigma=0.908, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7732 (+/-0.0168)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 19 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00132, rbf_sigma=8.1e-08, num_comp=11</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8621 (+/-0.00933)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 20 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=20.2, rbf_sigma=1.64e-09, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8494 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 21 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00173, rbf_sigma=0.126, num_comp=11</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8721 (+/-0.00749)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 22 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00853, rbf_sigma=0.989, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7369 (+/-0.0313)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 23 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00673, rbf_sigma=1.55e-10, num_comp=17</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.787 (+/-0.0485)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 24 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.871, rbf_sigma=1.72e-10, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.864 (+/-0.00842)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 25 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=3.8, rbf_sigma=6.24e-10, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.864 (+/-0.00842)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 26 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=5.2, rbf_sigma=0.791, num_comp=1</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7319 (+/-0.0173)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 27 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.213, rbf_sigma=9.11e-10, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8655 (+/-0.00848)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 28 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=6.99, rbf_sigma=3.03e-10, num_comp=0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8494 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 29 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00102, rbf_sigma=0.344, num_comp=5</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8631 (+/-0.0079)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 30 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=20.3, rbf_sigma=1.28e-05, num_comp=3</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8503 (+/-0.0112)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 31 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0012, rbf_sigma=3.75e-05, num_comp=7</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8634 (+/-0.00923)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 32 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0142, rbf_sigma=2.58e-10, num_comp=1</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7015 (+/-0.0374)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 33 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00411, rbf_sigma=0.557, num_comp=1</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.747 (+/-0.0173)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 34 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.161, rbf_sigma=0.167, num_comp=1</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7541 (+/-0.0177)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 35 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=2.48, rbf_sigma=0.783, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7748 (+/-0.014)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 36 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0138, rbf_sigma=0.624, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7938 (+/-0.0117)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 37 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00341, rbf_sigma=1.11e-10, num_comp=2</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7311 (+/-0.0404)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 38 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00113, rbf_sigma=1.48e-10, num_comp=14</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7888 (+/-0.0489)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 39 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=17.1, rbf_sigma=1.71e-10, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8638 (+/-0.00874)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 40 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=13.3, rbf_sigma=0.968, num_comp=17</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7691 (+/-0.0158)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 41 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0026, rbf_sigma=0.995, num_comp=3</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8496 (+/-0.0093)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 42 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=23.6, rbf_sigma=0.856, num_comp=13</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7972 (+/-0.0144)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 43 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00142, rbf_sigma=7.1e-06, num_comp=18</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8593 (+/-0.00882)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 44 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=31.4, rbf_sigma=1.7e-10, num_comp=15</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8616 (+/-0.00899)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 45 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8728 (@iter 15)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=31.4, rbf_sigma=0.0118, num_comp=6</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8779 (+/-0.00726)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 46 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8779 (@iter 45)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=11, rbf_sigma=0.718, num_comp=10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8247 (+/-0.0103)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 47 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8779 (@iter 45)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=27.1, rbf_sigma=3.61e-06, num_comp=8</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8645 (+/-0.00874)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 48 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8779 (@iter 45)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=20.4, rbf_sigma=1.23e-10, num_comp=4</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8513 (+/-0.0109)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 49 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8779 (@iter 45)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0011, rbf_sigma=0.677, num_comp=16</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8075 (+/-0.0119)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 50 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8779 (@iter 45)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00133, rbf_sigma=0.592, num_comp=14</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8311 (+/-0.014)</span>
</span></span></code></pre></div><p>The resulting tibble is a stacked set of rows of the rsample object with an additional column for the iteration number:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>search_res
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; #  10-fold cross-validation </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # A tibble: 510 x 5</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;    splits             id     .metrics         .notes           .iter</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  * &lt;list&gt;             &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;           &lt;dbl&gt;</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  1 &lt;split [1.4K/152]&gt; Fold01 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  2 &lt;split [1.4K/152]&gt; Fold02 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  3 &lt;split [1.4K/152]&gt; Fold03 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  4 &lt;split [1.4K/152]&gt; Fold04 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  5 &lt;split [1.4K/152]&gt; Fold05 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  6 &lt;split [1.4K/151]&gt; Fold06 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  7 &lt;split [1.4K/151]&gt; Fold07 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  8 &lt;split [1.4K/151]&gt; Fold08 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  9 &lt;split [1.4K/151]&gt; Fold09 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 10 &lt;split [1.4K/151]&gt; Fold10 &lt;tibble [5 × 6]&gt; &lt;tibble [0 × 1]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # … with 500 more rows</span>
</span></span></code></pre></div><p>As with grid search, we can summarize the results over resamples:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>estimates <span style="color:#666">&lt;-</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">collect_metrics</span>(search_res) <span style="color:#666">%&gt;%</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">arrange</span>(.iter)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>estimates
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # A tibble: 55 x 9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;        cost rbf_sigma num_comp .iter .metric .estimator  mean     n std_err</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;       &lt;dbl&gt;     &lt;dbl&gt;    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  1  0.00207  1.56e- 5       10     0 roc_auc binary     0.864    10 0.00888</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  2  0.0304   6.41e- 9        5     0 roc_auc binary     0.859    10 0.00922</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  3  0.348    4.43e- 2        1     0 roc_auc binary     0.757    10 0.0177 </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  4  1.45     2.04e- 3       15     0 roc_auc binary     0.865    10 0.00962</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  5 15.5      1.28e- 7       20     0 roc_auc binary     0.865    10 0.00848</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  6  0.580    1.54e- 9       12     1 roc_auc binary     0.862    10 0.00897</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  7  0.0251   6.36e- 6       16     2 roc_auc binary     0.861    10 0.00908</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  8 23.0      1.02e-10        7     3 roc_auc binary     0.863    10 0.00923</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  9  0.0894   1.09e-10        0     4 roc_auc binary     0.849    10 0.0116 </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 10  0.402    4.13e- 1       20     5 roc_auc binary     0.824    10 0.00885</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # … with 45 more rows</span>
</span></span></code></pre></div><p>The best performance of the initial set of candidate values was <code>AUC = 0.865 </code>. The best results were achieved at iteration 45 with a corresponding AUC value of 0.878. The five best results are:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">show_best</span>(search_res, metric <span style="color:#666">=</span> <span style="color:#ba2121">&#34;roc_auc&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # A tibble: 5 x 9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;       cost rbf_sigma num_comp .iter .metric .estimator  mean     n std_err</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;      &lt;dbl&gt;     &lt;dbl&gt;    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 1 31.4       0.0118         6    45 roc_auc binary     0.878    10 0.00726</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 2  0.0915    0.0300        20    15 roc_auc binary     0.873    10 0.00842</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 3  0.00173   0.126         11    21 roc_auc binary     0.872    10 0.00749</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 4  0.00210   0.0109        20    17 roc_auc binary     0.870    10 0.00881</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 5 11.8       0.00143       20    14 roc_auc binary     0.869    10 0.00837</span>
</span></span></code></pre></div><p>A plot of the search iterations can be created via:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">autoplot</span>(search_res, type <span style="color:#666">=</span> <span style="color:#ba2121">&#34;performance&#34;</span>)
</span></span></code></pre></div><img src="figs/bo-plot-1.svg" width="672" />
<p>There are many parameter combinations have roughly equivalent results.</p>
<p>How did the parameters change over iterations? Since two of the parameters are usually treated on the log scale, we can use <code>mutate()</code> to transform them, and then construct a plot using ggplot2:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">library</span>(tidyr)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#00f">collect_metrics</span>(search_res) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">select</span>(<span style="color:#666">-.</span>metric,<span style="color:#666">-.</span>estimator,<span style="color:#666">-</span>mean,<span style="color:#666">-</span>n,<span style="color:#666">-</span>std_err) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">mutate</span>(cost <span style="color:#666">=</span> <span style="color:#00f">log10</span>(cost), 
</span></span><span style="display:flex;"><span>         rbf_sigma <span style="color:#666">=</span> <span style="color:#00f">log10</span>(rbf_sigma)) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">pivot_longer</span>(cols <span style="color:#666">=</span> <span style="color:#00f">c</span>(<span style="color:#666">-.i</span>ter),
</span></span><span style="display:flex;"><span>               names_to <span style="color:#666">=</span> <span style="color:#ba2121">&#34;parameter&#34;</span>,
</span></span><span style="display:flex;"><span>               values_to <span style="color:#666">=</span> <span style="color:#ba2121">&#34;value&#34;</span>) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">ggplot</span>(<span style="color:#00f">aes</span>(x <span style="color:#666">=</span> .iter, y <span style="color:#666">=</span> value)) <span style="color:#666">+</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">geom_point</span>() <span style="color:#666">+</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">facet_wrap</span>( <span style="color:#666">~</span> parameter, scales <span style="color:#666">=</span> <span style="color:#ba2121">&#34;free_y&#34;</span>)
</span></span></code></pre></div><img src="figs/bo-param-plot-1.svg" width="672" />




<h2 id="session-information">Session information
  <a href="#session-information">
    <svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg>
  </a>
</h2><pre tabindex="0"><code>#&gt; ─ Session info ───────────────────────────────────────────────────────────────
#&gt;  setting  value                       
#&gt;  version  R version 3.6.2 (2019-12-12)
#&gt;  os       macOS Mojave 10.14.6        
#&gt;  system   x86_64, darwin15.6.0        
#&gt;  ui       X11                         
#&gt;  language (EN)                        
#&gt;  collate  en_US.UTF-8                 
#&gt;  ctype    en_US.UTF-8                 
#&gt;  tz       America/Denver              
#&gt;  date     2020-04-17                  
#&gt; 
#&gt; ─ Packages ───────────────────────────────────────────────────────────────────
#&gt;  package    * version date       lib source        
#&gt;  broom      * 0.5.5   2020-02-29 [1] CRAN (R 3.6.0)
#&gt;  dials      * 0.0.6   2020-04-03 [1] CRAN (R 3.6.2)
#&gt;  dplyr      * 0.8.5   2020-03-07 [1] CRAN (R 3.6.0)
#&gt;  ggplot2    * 3.3.0   2020-03-05 [1] CRAN (R 3.6.0)
#&gt;  infer      * 0.5.1   2019-11-19 [1] CRAN (R 3.6.0)
#&gt;  kernlab    * 0.9-29  2019-11-12 [1] CRAN (R 3.6.0)
#&gt;  modeldata  * 0.0.1   2019-12-06 [1] CRAN (R 3.6.0)
#&gt;  parsnip    * 0.1.0   2020-04-09 [1] CRAN (R 3.6.2)
#&gt;  purrr      * 0.3.3   2019-10-18 [1] CRAN (R 3.6.0)
#&gt;  recipes    * 0.1.10  2020-03-18 [1] CRAN (R 3.6.0)
#&gt;  rlang      * 0.4.5   2020-03-01 [1] CRAN (R 3.6.0)
#&gt;  rsample    * 0.0.6   2020-03-31 [1] CRAN (R 3.6.2)
#&gt;  tibble     * 2.1.3   2019-06-06 [1] CRAN (R 3.6.2)
#&gt;  tidymodels * 0.1.0   2020-02-16 [1] CRAN (R 3.6.0)
#&gt;  tidyr      * 1.0.2   2020-01-24 [1] CRAN (R 3.6.0)
#&gt;  tune       * 0.1.0   2020-04-02 [1] CRAN (R 3.6.2)
#&gt;  workflows  * 0.1.1   2020-03-17 [1] CRAN (R 3.6.0)
#&gt;  yardstick  * 0.0.6   2020-03-17 [1] CRAN (R 3.6.0)
#&gt; 
#&gt; [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
</code></pre>
      </div>


      

      </div> 
      
      <div class="column25">
        <div class="section hideOnMobile">
          
          <div class="sectionTitle">Contents</div>
            <nav id="TableOfContents">
  <ul>
    <li><a href="#introduction">Introduction</a></li>
    <li><a href="#cell-segmenting-revisited">Cell segmenting revisited</a></li>
    <li><a href="#the-tuning-scheme">The tuning scheme</a></li>
    <li><a href="#sequential-tuning">Sequential tuning</a></li>
    <li><a href="#session-information">Session information</a></li>
  </ul>
</nav>
          
        </div>
        <div class="section">
          





        </div>
      </div> 

    </div> 
  </div>  
</div> 



        <div id="rStudioFooter" class="band">
          <div class="bandContent">
            <div id="copyright">
              
              
            </div>
            <div id="logos">
              <a href="" class="footerLogo gitHub" aria-label="Tidyverse GitHub organization"></a>
              <a href="" class="footerLogo twitter" aria-label="rstats hashtag on twitter.com"></a>
            </div>
          </div>
        </div>

      </div>  
    </div>  

    




<script src="//cdn.bootcss.com/highlight.js//highlight.min.js"></script>



<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>




    
<script src="/js/math-code.js"></script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    processEscapes: true
  }
});
</script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    

  </body>
</html>

</body>
</html>
